# Generated by Django 3.2.9 on 2022-01-15 19:16

from django.db import migrations
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission

User = get_user_model()

def run_seed(apps, schema_editor):
    group, created = Group.objects.get_or_create(name='admin')
    permissions = Permission.objects.all().values_list('id', flat=True)
    group.permissions.add(*permissions)
    user = User.objects.create_user(
            first_name="admin",
            last_name="user",
            username="admin",
            password="123456",
            email="admin@admin.com",
            profile_img="",
            is_superuser=1
        )
    user.groups.add(group)

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run_seed),
    ]
