# Generated by Django 3.2.9 on 2022-01-25 07:25

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'technologies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('overview_document', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('ssh_details', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('cpanel_details', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('ftp_details', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('key_link_url', encrypted_model_fields.fields.EncryptedTextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('technologies', models.ManyToManyField(blank=True, to='projects.Technology', verbose_name='technologies')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
